import localFont from "next/font/local";
import "./globals.css";

const geistMono = localFont({
  src: "./fonts/Metropolis-Regular.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const geistMonoBold = localFont({
  src: "./fonts/Metropolis-Bold.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Zádiel Ubytovanie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistMonoBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}